use_frameworks!

platform :ios, '8.0'

target 'tkCommonlib_Example' do
  pod 'tkCommonlib', :path => '../'

  target 'tkCommonlib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
